######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 15 22:46:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mediaplayer.h
FORMS += settings.ui
SOURCES += main.cpp meidaplayer.cpp
QT += phonon
